### ISSUE TITLE
[BUG] Could not sign up

### ISSUE THREAD

**Issue by NghiaTranUIT** [8bitzz/COSC2101#83]
### Description
For some reason, I could not sign up for a new account.

<img width="1601" alt="Screen_Shot_2021-08-20_at_08_48_23" src="https://user-images.githubusercontent.com/5878421/130166306-80dbb98f-3b52-477b-9911-5122973e7f1d.png">

### How to reproduce
1. Click on Sign Up button
2. Enter username, email and password=123123123
3. Click Register
4. Observe that there is nothing happen

=> Check the Network => The request is failed due to Password validation in the backend

### Expectation
- Able to create an account
- Show the error message from a response (Use Badge, not Alert)
- Should not display an Alert

**Comment by hongnguyen0112** [comment]
Is this will be solved in the user input validation issue? I will do it next week?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
